version: '3'
services:
  api:
    image: node:fermium-alpine
    command: npm run dev
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    restart: "on-failure"
    volumes:
      - ./:/app
    working_dir: /app
    networks:
      - nw
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - nw
networks:
  nw:
    