version: '3'
services:
  api:
    image: node:fermium-alpine
    command: npm run dev
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    network:
      - nw
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    network:
      - nw
networks:
  nw:
    